version: "3.8"
services:
  ng:
    image: nginx
    hostname: ng
    deploy:
      replicas: 3
    ports: 
      - 80:80
      - 8080:80
    depends_on: 
      - kc
    configs:
      - source: nginx.default.conf
        target: /etc/nginx/conf.d/default.conf 

  kc:
    image: wangsying/keycloak
    hostname: kc
    deploy:
      replicas: 3
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin 
      KEYCLOAK_FRONTEND_URL: http://centos1/auth
      KEYCLOAK_HOSTNAME: centos1
      DB_VENDOR: mariadb
      DB_ADDR: 192.168.3.181
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      PROXY_ADDRESS_FORWARDING: 'true'
      JGROUPS_DISCOVERY_EXTERNAL_IP: 10.10.0.4
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING

networks:
  default:
    external:
      name: keycloak_net

configs:
  nginx.default.conf:
    file: ./conf/swarm/conf/nginx/default.conf